In [1]:
#This code allows to output more than one variable value without using a print statement.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# InteractiveShell.ast_node_interactivity = "last_expr"

In [2]:
# Version Check
import sys
import tensorflow as tf
import tensorflow_datasets as tfds
import PIL
import pandas as pd
import numpy as np
import scipy
print("python", sys.version)
print("tensorflow", tf.__version__)
print("tensorflow-datasets", tfds.__version__)
print("Pillow", PIL.__version__)
print("pandas", pd.__version__)
print("numpy", np.__version__)
print("scipy", scipy.__version__)
print()
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("Built with GPU support:", tf.test.is_built_with_gpu_support())

python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
tensorflow 2.6.2
tensorflow-datasets 4.4.0
Pillow 8.3.2
pandas 1.3.3
numpy 1.19.5
scipy 1.7.1

Num GPUs Available: 1
Built with CUDA: True
Built with GPU support: True


## indexing

In [3]:
vec = tf.constant([10, 20, 30, 40, 50])
vec

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [4]:
vec[0]
vec[-1]
vec[:3]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

<tf.Tensor: shape=(), dtype=int32, numpy=50>

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [5]:
mat = tf.constant([[10, 20, 30], 
                   [40, 50, 60]])
mat

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

In [6]:
mat[0, 2]
mat[0, :]
mat[:, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=30>

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 50])>

In [7]:
tensor = tf.constant([
    [[10, 20, 30], 
     [40, 50, 60]],
    [[-10, -20, -30], 
     [-40, -50, -60]]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[-10, -20, -30],
        [-40, -50, -60]]])>

In [8]:
tensor[0, :, :]
tensor[:, :2, :2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60]])>

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 10,  20],
        [ 40,  50]],

       [[-10, -20],
        [-40, -50]]])>

## tf.reshape

In [9]:
tensor = tf.constant(range(0, 24))
tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [10]:
tensor1 = tf.reshape(tensor, [3, 8])
tensor1

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])>

In [11]:
tensor2 = tf.reshape(tensor1, [-1, 4])
tensor2

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])>

In [12]:
tensor3 = tf.reshape(tensor2, [-1])
tensor3

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [13]:
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
tensor4

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [14]:
tensor5 = tf.reshape(tensor4, [3, 2, 4])
tensor5

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [15]:
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
tensor6

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])>

## tf.Variable(name=" "), tf.convert_to_tensor

In [16]:
tensor1 = tf.constant([[0, 1, 2], 
                       [3, 4, 5]])
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [17]:
tensor_var1 = tf.Variable(tensor1)
tensor_var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>

In [18]:
tensor_var1.name
tensor_var1.shape
tensor_var1.dtype
tensor_var1.numpy()

'Variable:0'

TensorShape([2, 3])

tf.int32

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
tensor_var1.assign([[1, 1, 1], 
                    [2, 2, 2]])
tensor_var1

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [20]:
tensor2 = tf.convert_to_tensor(tensor_var1)
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [21]:
tensor_var2 = tf.Variable(tensor2, name='New Name')
tensor_var2

<tf.Variable 'New Name:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [22]:
tensor_var2.name
tensor_var2.shape
tensor_var2.dtype
tensor_var2.numpy()

'New Name:0'

TensorShape([2, 3])

tf.int32

array([[1, 1, 1],
       [2, 2, 2]])

In [23]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]])>

## automatic differentiation

In [24]:
InteractiveShell.ast_node_interactivity = "last_expr"

In [25]:
# generate a dataset that has a linear relationship

g = tf.random.Generator.from_seed(2022)
x = g.normal(shape=(10, ))
y = 3*x - 2

In [26]:
x
y

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-3.3320663 ,  1.9145031 , -4.15687   , -1.8921382 ,  0.69796014,
       -3.8876352 ,  0.8313656 , -4.6462264 ,  0.7089119 , -1.7484705 ],
      dtype=float32)>

In [27]:
# define loss function

def cal_mse(x, y, a, b):
    
    y_pred = a*x + b
    squared_error = (y_pred - y)**2
    mean_squared_error = tf.reduce_mean(squared_error)
    
    return mean_squared_error

In [28]:
# record automatic differentiation using tf.GradientTape

# initial values
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS + 1):
    
    with tf.GradientTape() as tape:
        mse = cal_mse(x, y, a, b)
   
    grad = tape.gradient(mse, {'a': a, 'b': b})
    d_a, d_b = grad['a'], grad['b']
    
    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)
    
    if epoch % 20 == 0:
        print("EPOCH: %d - MSE: %.4f - a: %.2f - b: %.2f" %(epoch, mse, a, b))

EPOCH: 20 - MSE: 0.7736 - a: 1.99 - b: -1.55
EPOCH: 40 - MSE: 0.0758 - a: 2.68 - b: -1.88
EPOCH: 60 - MSE: 0.0075 - a: 2.90 - b: -1.96
EPOCH: 80 - MSE: 0.0008 - a: 2.97 - b: -1.99
EPOCH: 100 - MSE: 0.0001 - a: 2.99 - b: -2.00
EPOCH: 120 - MSE: 0.0000 - a: 3.00 - b: -2.00
EPOCH: 140 - MSE: 0.0000 - a: 3.00 - b: -2.00
EPOCH: 160 - MSE: 0.0000 - a: 3.00 - b: -2.00
EPOCH: 180 - MSE: 0.0000 - a: 3.00 - b: -2.00
EPOCH: 200 - MSE: 0.0000 - a: 3.00 - b: -2.00
