In [1]:
#This code allows to output more than one variable value without using a print statement.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Version Check
import sys
import tensorflow as tf
import tensorflow_datasets as tfds
import PIL
import pandas as pd
import numpy as np
import scipy
print("python", sys.version)
print("tensorflow", tf.__version__)
print("tensorflow-datasets", tfds.__version__)
print("Pillow", PIL.__version__)
print("pandas", pd.__version__)
print("numpy", np.__version__)
print("scipy", scipy.__version__)
print()
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("Built with GPU support:", tf.test.is_built_with_gpu_support())

python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
tensorflow 2.6.2
tensorflow-datasets 4.4.0
Pillow 8.3.2
pandas 1.3.3
numpy 1.19.5
scipy 1.7.1

Num GPUs Available: 1
Built with CUDA: True
Built with GPU support: True


## Scalar (rank-0 tensor)

In [3]:
a = tf.constant(1)
b = tf.constant(2)

In [4]:
a
b

<tf.Tensor: shape=(), dtype=int32, numpy=1>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
tf.rank(a)
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
tf.math.add(a, b)
tf.math.subtract(a, b)
tf.math.multiply(a, b)
tf.math.divide(a, b)
tf.math.mod(a, b)        # quotient
tf.math.floordiv(a, b)   # remainder

<tf.Tensor: shape=(), dtype=int32, numpy=3>

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<tf.Tensor: shape=(), dtype=float64, numpy=0.5>

<tf.Tensor: shape=(), dtype=int32, numpy=1>

<tf.Tensor: shape=(), dtype=int32, numpy=0>

## Vector (rank-1 tensor)

In [7]:
vec1 = tf.constant([10., 20., 30.])
vec2 = tf.constant(np.array([10., 20., 30,]), dtype='float32')   # for the same dtype

In [8]:
vec1
vec2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>

In [9]:
tf.rank(vec1)
tf.rank(vec2)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [10]:
tf.math.add(vec1, vec2)        # cannot calculate if dtypes are different
tf.math.subtract(vec1, vec2)
tf.math.multiply(vec1, vec2)
tf.math.divide(vec1, vec2)
tf.math.mod(vec1, vec2)        # quotient 
tf.math.floordiv(vec1, vec2)   # remainder

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([20., 40., 60.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100., 400., 900.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [11]:
vec1 + vec2
vec1 - vec2
vec1 * vec2
vec1 / vec2
vec1 % vec2    # quotient
vec1 // vec2   # remainder

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([20., 40., 60.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100., 400., 900.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [12]:
tf.reduce_sum(vec1)
sum(vec1)

<tf.Tensor: shape=(), dtype=float32, numpy=60.0>

<tf.Tensor: shape=(), dtype=float32, numpy=60.0>

In [13]:
tf.square(vec1)
tf.math.sqrt(vec1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100., 400., 900.], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.1622777, 4.4721355, 5.4772253], dtype=float32)>

In [14]:
vec1**2
vec1**(1/2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 99.99999, 400.     , 899.99994], dtype=float32)>

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.1622777, 4.472136 , 5.477226 ], dtype=float32)>

In [15]:
vec1 + 1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([11., 21., 31.], dtype=float32)>

## Matrix (rank-2 tensor)

In [16]:
mat1 = tf.constant([[10, 20, 30], 
                    [10, 20, 30]], dtype='float32')
mat2 = tf.stack([vec1, vec2])

In [17]:
mat1
mat2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [10., 20., 30.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [10., 20., 30.]], dtype=float32)>

In [18]:
tf.rank(mat1)
tf.rank(mat2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
tf.math.add(mat1, mat2)        # cannot calculate if dtypes are different
tf.math.subtract(mat1, mat2)
tf.math.multiply(mat1, mat2)
tf.math.divide(mat1, mat2)
tf.math.mod(mat1, mat2)        # quotient 
tf.math.floordiv(mat1, mat2)   # remainder

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[20., 40., 60.],
       [20., 40., 60.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[100., 400., 900.],
       [100., 400., 900.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
mat1 + mat2
mat1 - mat2
mat1 * mat2
mat1 / mat2
mat1 % mat2    # quotient
mat1 // mat2   # remainder

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[20., 40., 60.],
       [20., 40., 60.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[100., 400., 900.],
       [100., 400., 900.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [21]:
tf.math.add(mat1, 100)        # cannot calculate if dtypes are different
tf.math.subtract(mat1, 100)
tf.math.multiply(mat1, 100)
tf.math.divide(mat1, 100)
tf.math.mod(mat1, 100)        # quotient 
tf.math.floordiv(mat1, 100)   # remainder

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[110., 120., 130.],
       [110., 120., 130.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-90., -80., -70.],
       [-90., -80., -70.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1000., 2000., 3000.],
       [1000., 2000., 3000.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.1, 0.2, 0.3],
       [0.1, 0.2, 0.3]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [10., 20., 30.]], dtype=float32)>

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [22]:
from tensorflow.python.ops.numpy_ops import np_config
np_config.enable_numpy_behavior()

tf.matmul(mat1, mat2.T)   # matrix mulptiply

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1400., 1400.],
       [1400., 1400.]], dtype=float32)>

In [23]:
tf.matmul(mat1, mat2.T).numpy()   # convert to numpy array

array([[1400., 1400.],
       [1400., 1400.]], dtype=float32)

## Tensor

In [24]:
mat1 = [[1, 2, 3, 4], 
        [5, 6, 7, 8]]

mat2 = [[9, 10, 11, 12], 
        [13, 14, 15, 16]]

mat3 = [[17, 18, 19, 20], 
        [21, 22, 23, 24]]

# mat2 = [[j+8 for j in i] for i in mat1]

In [25]:
tensor1 = tf.constant([mat1, mat2, mat3])
tensor1

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [26]:
tf.rank(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [27]:
tensor2 = tf.stack([tensor1, tensor1])
tensor2

<tf.Tensor: shape=(2, 3, 2, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]]])>

In [28]:
tf.rank(tensor2)

<tf.Tensor: shape=(), dtype=int32, numpy=4>