In [1]:
# # This code allows to output more than one variable value without using a print statement.
# from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity = "all"

# # Default
# # InteractiveShell.ast_node_interactivity = "last_expr"

In [2]:
# Version Check
import sys
import tensorflow as tf
import tensorflow_datasets as tfds
import PIL
import pandas as pd
import numpy as np
import scipy
print("python", sys.version)
print("tensorflow", tf.__version__)
print("tensorflow-datasets", tfds.__version__)
print("Pillow", PIL.__version__)
print("pandas", pd.__version__)
print("numpy", np.__version__)
print("scipy", scipy.__version__)
print()
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
print("Built with CUDA:", tf.test.is_built_with_cuda())
print("Built with GPU support:", tf.test.is_built_with_gpu_support())

python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)]
tensorflow 2.6.2
tensorflow-datasets 4.4.0
Pillow 8.3.2
pandas 1.3.3
numpy 1.19.5
scipy 1.7.1

Num GPUs Available: 1
Built with CUDA: True
Built with GPU support: True


## cifar100

In [3]:
ds = tfds.load('cifar100', split='train')
ds

<PrefetchDataset shapes: {coarse_label: (), id: (), image: (32, 32, 3), label: ()}, types: {coarse_label: tf.int64, id: tf.string, image: tf.uint8, label: tf.int64}>

In [4]:
for data in ds.take(1):
    print(type(data))

<class 'dict'>


In [5]:
for data in ds.take(1):
    print(data)

{'coarse_label': <tf.Tensor: shape=(), dtype=int64, numpy=12>, 'id': <tf.Tensor: shape=(), dtype=string, numpy=b'train_16399'>, 'image': <tf.Tensor: shape=(32, 32, 3), dtype=uint8, numpy=
array([[[151, 154, 145],
        [144, 147, 135],
        [141, 143, 134],
        ...,
        [ 44,  38,  39],
        [112, 100,  96],
        [145, 127, 120]],

       [[153, 156, 150],
        [141, 144, 135],
        [139, 142, 136],
        ...,
        [ 68,  59,  59],
        [131, 113, 106],
        [121, 101,  94]],

       [[163, 165, 161],
        [150, 153, 145],
        [147, 149, 144],
        ...,
        [ 75,  66,  60],
        [101,  86,  77],
        [ 83,  77,  73]],

       ...,

       [[150, 150, 162],
        [ 51,  52,  67],
        [ 46,  42,  56],
        ...,
        [ 60,  59,  48],
        [ 71,  73,  56],
        [ 58,  62,  44]],

       [[146, 158, 168],
        [ 92, 106, 116],
        [ 73,  77,  85],
        ...,
        [ 54,  55,  40],
        [ 59,  66,  41],
 

In [6]:
for data in ds.take(10):
    image = data['image']
    label = data['label']
    print(f'image shape: {image.shape}, label: {label.numpy()}')

image shape: (32, 32, 3), label: 66
image shape: (32, 32, 3), label: 23
image shape: (32, 32, 3), label: 40
image shape: (32, 32, 3), label: 39
image shape: (32, 32, 3), label: 7
image shape: (32, 32, 3), label: 15
image shape: (32, 32, 3), label: 11
image shape: (32, 32, 3), label: 44
image shape: (32, 32, 3), label: 76
image shape: (32, 32, 3), label: 50


In [7]:
# as_supervised=True: load as tuple (instead of dictionary)
ds = tfds.load('cifar100', split='train', as_supervised=True)

for image, label in ds.take(10):
    print(f'image shape: {image.shape}, label: {label.numpy()}')

image shape: (32, 32, 3), label: 66
image shape: (32, 32, 3), label: 23
image shape: (32, 32, 3), label: 40
image shape: (32, 32, 3), label: 39
image shape: (32, 32, 3), label: 7
image shape: (32, 32, 3), label: 15
image shape: (32, 32, 3), label: 11
image shape: (32, 32, 3), label: 44
image shape: (32, 32, 3), label: 76
image shape: (32, 32, 3), label: 50


In [8]:
# with_info=True: load info as well
ds, info = tfds.load('cifar100', split='train', as_supervised=True, with_info = True)
info

tfds.core.DatasetInfo(
    name='cifar100',
    full_name='cifar100/3.0.2',
    description="""
    This dataset is just like the CIFAR-10, except it has 100 classes containing 600 images each. There are 500 training images and 100 testing images per class. The 100 classes in the CIFAR-100 are grouped into 20 superclasses. Each image comes with a "fine" label (the class to which it belongs) and a "coarse" label (the superclass to which it belongs).
    """,
    homepage='https://www.cs.toronto.edu/~kriz/cifar.html',
    data_path='C:\\Users\\hawoo\\tensorflow_datasets\\cifar100\\3.0.2',
    download_size=160.71 MiB,
    dataset_size=132.03 MiB,
    features=FeaturesDict({
        'coarse_label': ClassLabel(shape=(), dtype=tf.int64, num_classes=20),
        'id': Text(shape=(), dtype=tf.string),
        'image': Image(shape=(32, 32, 3), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=100),
    }),
    supervised_keys=('image', 'label'),
    disable_shu